# Generated by Django 4.2.7 on 2023-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=255)),
                ('student_email', models.EmailField(max_length=50)),
                ('personal_email', models.EmailField(max_length=50)),
                ('locker_number', models.IntegerField()),
                ('locker_combination', models.CharField(max_length=10)),
                ('good_student', models.BooleanField(default=False)),
            ],
        ),
    ]
