# Generated by Django 4.2.7 on 2023-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
