# Generated by Django 4.2.7 on 2023-11-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_personal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(unique=True),
        ),
    ]
