# Generated by Django 4.2.7 on 2023-11-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_student_locker_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
