# Generated by Django 4.2.7 on 2023-11-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
